version: '3.8'
services:
  backend:
    build: ./backend
    container_name: todo_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - SECRET_KEY=${SECRET_KEY}
    restart: always

  frontend:
    build: ./frontend
    container_name: todo_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
    
