# .github/workflows/ci.yml

name: CI Pipeline

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # Backend dependency check
  backend-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install backend dependencies
        run: pip install -r backend/requirements.txt

      # - name: Run linting with Flake8
      #   run: flake8 backend/

  # Frontend dependency check
  frontend-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: npm --prefix frontend install

      # - name: Linting with ESlint
      #   run: npm --prefix frontend run lint

  # Docker build check
  docker-build-check:
    runs-on: ubuntu-latest
    needs: [backend-check, frontend-check]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # Install Docker CLI
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: docker compose -f docker-compose.yml build
