name: CI Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r backend/requirements.txt

      # --- NEW STEP ADDED ---
      - name: Lint with flake8
        run: flake8 backend/

  frontend-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm --prefix frontend install

      # --- NEW STEP ADDED ---
      - name: Lint with ESLint
        run: npm --prefix frontend run lint

  docker-build-check:
    runs-on: ubuntu-latest
    needs: [backend-check, frontend-check]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build the Docker images
        run: docker-compose build